### ISSUE TITLE
Enrichment analysis might be faulty

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/Evidente2.0#26]
I think there is a mistake in the implementation of the enrichment analysis. If we take a look at Sophie's Bachelor thesis (pg. 28), the SNPs that are found in the internal nodes are also accounted for the Fishers Exact Test, however, these SNPs do not exist as such i.e they are fictive appearances of the SNPs that are already considered from the leaves of the tree. This produces a larger N (a+b+c+d) than the number of SNPs that actually exist within the data. I think that N should be the number of SNPs that are found within a gene, i.e. the number of non-reference appearances in the SNP-table that are found within a gene.

**Comment by ThHarbig** [comment]
I think this is intentional and we discussed this during the thesis. I also remember that initially I had the same thoughts as you do but something convinced me that Sophies implementation has some advantages. But right now I don't remember the rationale behind it. I think we should discuss this and ask her if we do not remember it. Maybe we can also find it in the thesis?

**Comment by mwittep** [comment]
new enrichment analysis method implemented in ac7eb8c35bc741d5fc4c6d5fe202ceaf1c4a957d
